StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{5EB477E3E74EE696}" {
   Id "GRAD-Author-nomisum"
   Target_en_us "nomisum"
   Modified 1588889564
   Author "y0014984"
   LastChanged "y0014984"
  }
  CustomStringTableItem "{5EB477E3EDF22410}" {
   Id "GRAD-Author-nomisum-and-sebastian"
   Target_en_us "nomisum + y0014984|Sebastian"
   Modified 1588890318
   Author "y0014984"
   LastChanged "y0014984"
  }
  CustomStringTableItem "{5EB477E3EE71B546}" {
   Id "GRAD-Author-sebastian"
   Target_en_us "y0014984|Sebastian"
   Modified 1588890328
   Author "y0014984"
   LastChanged "y0014984"
  }
  CustomStringTableItem "{5EB477E2A703D135}" {
   Id "GRAD-COOP-GameMode"
   Target_en_us "COOP"
   Modified 1588889549
   Author "y0014984"
   LastChanged "y0014984"
  }
  CustomStringTableItem "{5EB477EBE4128EB7}" {
   Id "GRAD-GM-Eden-Description"
   Target_en_us "Gruppe Adler COOP Template. Use the load/save buttons in Game Master to deploy your mission. Have fun."
   Modified 1588891841
   Author "y0014984"
   LastChanged "y0014984"
  }
  CustomStringTableItem "{5EB477E3647013B7}" {
   Id "GRAD-GM-Eden-Mission-Name"
   Target_en_us "GRAD - Game Master - Everon"
   Modified 1588893504
   Author "y0014984"
   LastChanged "y0014984"
  }
 }
}