StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{5EB4C748AB168D72}" {
   Id "GRAD-Author-nomisum-and-sebastian"
   Target_en_us "nomisum + y0014984|Sebastian"
   Modified 1588906619
   Author "y0014984"
   LastChanged "y0014984"
  }
  CustomStringTableItem "{5EB4C748C4CDE9CB}" {
   Id "GRAD-GM-Eden-Description"
   Target_en_us "Gruppe Adler COOP Template. Use the load/save buttons in Game Master to deploy your mission. Have fun."
   Modified 1588906424
   Author "y0014984"
   LastChanged "y0014984"
  }
 }
}